[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for blog posts
[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200

# Headers for better SEO and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling for contact forms
[[forms]]
  name = "contact"

# Environment variables (set these in Netlify dashboard)
# EMAILJS_SERVICE_ID
# EMAILJS_TEMPLATE_ID  
# EMAILJS_PUBLIC_KEY